#table_name=${1^^}
echo table_name=cars
echo user_name=cloudera-scm
echo remote_db_name=scm
full_table_name=${remote_db_name}.${table_name}
staging_table=${table_name}_STAGE
partitioned_table=${table_name}_PART
merged_table=${table_name}_MERGE
echo db_name=scm
echo top_dir=jeffTestData/
staging_dir=${top_dir}/sqoop
echo metadata_dir=${top_dir}/metadata
archive_dir=${top_dir}/archive
schema_name=${table_name}.schema
echo password_file=${top_dir}/sqoop.password
mappers=${2-4}
job_name=${table_name}_JOB
#check_column="decode(created_date,null,modified_date,modified_date,null,created_date,greatest(created_date,modified_date))"
check_column="nvl(nvl(greatest(created_date,modified_date),modified_date),created_date)"
echo connect_string=!connect jdbc:hive2://azh7-1.ent.cloudera.com:10000/default;
partition_column=created_date
curr_date=`date +"%Y_%m_%d_%H_%M"`
sqoop_metastore=jdbc:hsqldb:hsql://pzxdap5priv:16000/sqoop
